"""Observed, ground-truth-free ROS 2 placement adapter."""

from .attached_collision import (
    AttachedCollisionAuditConfig,
    AttachedCollisionSnapshot,
    AttachedObjectPathAuditor,
)
from .core import (
    backproject_depth,
    CandidateAudit,
    capture_observed_region_geometry,
    capture_planned_object_geometry,
    combine_trajectory_segments,
    EvaluatedPlacementMotion,
    ObservedPerceptionIdentity,
    ObservedPlacementRegionGeometry,
    parse_region_request,
    PlaceExecutionCorrelation,
    PlacementCoordinator,
    PlacementOrientationVerification,
    PlacementOutput,
    PlacementPerceptionSnapshot,
    PlacementRegionRequest,
    PlacementTrajectoryContract,
    PlannedObjectGeometry,
    PostReleaseObservation,
    PostReleasePlacementVerifier,
    PostReleaseVerificationConfig,
    PostReleaseVerificationResult,
    RawTrajectorySegment,
    TrajectoryWaypoint,
)

__all__ = [
    'AttachedCollisionAuditConfig',
    'AttachedCollisionSnapshot',
    'AttachedObjectPathAuditor',
    'CandidateAudit',
    'ObservedPerceptionIdentity',
    'ObservedPlacementRegionGeometry',
    'EvaluatedPlacementMotion',
    'PlacementCoordinator',
    'PlaceExecutionCorrelation',
    'PlacementOutput',
    'PlacementOrientationVerification',
    'PlacementPerceptionSnapshot',
    'PlacementRegionRequest',
    'PlacementTrajectoryContract',
    'PlannedObjectGeometry',
    'PostReleaseObservation',
    'PostReleasePlacementVerifier',
    'PostReleaseVerificationConfig',
    'PostReleaseVerificationResult',
    'RawTrajectorySegment',
    'TrajectoryWaypoint',
    'backproject_depth',
    'capture_observed_region_geometry',
    'capture_planned_object_geometry',
    'combine_trajectory_segments',
    'parse_region_request',
]
